### PR TITLE
Do not disable side volume buttons in tablet mode

### PR DESCRIPTION
**Pull request by ChocolateLoverRaj**
For more information: https://bugzilla.redhat.com/show_bug.cgi?id=2048628, and https://gitlab.freedesktop.org/libinput/libinput/-/merge_requests/741

### CODE REVIEW

**Comment by WeirdTreeThing** [comment]
The side buttons are not handled by AT Keyboard. On intel it is the `intel virtual buttons`.

**Comment by ChocolateLoverRaj** [comment]
> The side buttons are not handled by AT Keyboard. On intel it is the `intel virtual buttons`.

I used `evtest` to investigate which input the side buttons are and for jinlon it is AT keyboard.

**Comment by ChocolateLoverRaj** [comment]
Also, what really matters is fact the one line I changed for libinput quirks fixes the issue.
Without keyd: Side buttons work in tablet mode
With keyd: Side buttons don't work in tablet mode
With keyd + the quirk I added: Side buttons work in tablet mode

**Comment by WeirdTreeThing** [comment]
wtf google

**Comment by WeirdTreeThing** [comment]
so just checked, intel virtual buttons exists but seems to do nothing

**Pull request merged**
