### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by jenneron**

### CODE REVIEW

**Comment by WeirdTreeThing** [comment]
Thanks for refactoring this, I've been neglecting it.

**Comment by WeirdTreeThing** [comment]
What else do you still need to do?

**Comment by jenneron** [comment]
> What else do you still need to do?

You had 4 similar blocks of code, i unified it into `get_functional_row()` function. I hope it will make easier to make "inverted" function. I'm looking at it right now

**Comment by WeirdTreeThing** [comment]
Yeah that was one thing I was lazy about when I first wrote it

**Comment by jenneron** [comment]
Also, since this function will use 3 variables: `use_vivaldi`, `super_is_held` and `super_inverted` it means that we will have a lot of possible combinations, and to avoid mistakes we will probably have to write a few tests for this function

**Pull request merged**
